---
- hosts: all
  vars:
    ansible_bender:
      base_image: registry.access.redhat.com/ubi8/ubi

      target_image:
        name: myimage
        labels:
          built-by: '{{ ansible_user }}'
        environment:
          FOO: bar
  tasks:
  - dnf: 
      name: mc 
      state: latest

